syncSource:
  replicaSet:
    hostAndPort: "mongodb:27017"
    scramAuth:
      username: "mongotUser"
      passwordFile: "/auth/passwordFile"
      authSource: "admin"
      tls:
        enabled: false

storage:
  dataPath: "/data/mongot"

server:
  grpc:
    address: "mongot:27028"
    tls:
      mode: "disabled"

metrics:
  enabled: true
  address: "mongot:9946"

healthCheck:
  address: "mongot:8080"

logging:
  verbosity: INFO

query:
  lucene:
    enableConcurrentSearch: true